[versions]
checkerframework = "3.26.0"
jmh = "1.27"

[libraries]
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
checker = { group = "org.checkerframework", name = "checker", version.ref = "checkerframework" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.7.0" }

[bundles]

[plugins]
checkerframework = { id = "org.checkerframework", version = "1.0.2" }
jreleaser = { id = "org.jreleaser", version = "1.22.0" }
